apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: test
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: youssefrm/ecomm-front_test
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: test
spec:
  type: NodePort
  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
  selector:
    app: front
