# product.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: youssefrm/ecomm-product_test
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - port: 8081
      targetPort: 8081

