apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000  # Ensures the group ownership is correct
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          runAsUser: 0  # Run as root to change ownership
        volumeMounts:
        - name: es-storage
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: elasticsearch:8.11.1
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: ELASTIC_USERNAME
          value: "elastic"
        - name: ELASTIC_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ELASTICSEARCH_PASSWORD
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: CLI_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: bootstrap.memory_lock
          value: "true"
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.enrollment.enabled
          value: "false"
        volumeMounts:
        - name: es-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-storage
        persistentVolumeClaim:
          claimName: es-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: prod
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  type: ClusterIP
