apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: youssefrm/ecomm-gateway_test
          ports:
            - containerPort: 8091
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: test
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - nodePort: 30009
      port: 8091
      targetPort: 8091
